### ISSUE TITLE
Verbosity for javascript Error

### ISSUE THREAD

**Issue by Aetet** [zerkalica/immutable-di#1]
Usage of this string is not safe:
var _path = dep.definition.__di.path;      define.js:51

If we pass undefined to \@stateful we got an error:
Uncaught TypeError: Cannot read property '__di' of undefined

If we mistyping:
var facet = Facet({deps}, func);
We got:
Uncaught TypeError: Cannot read property 'path' of undefined

**Comment by zerkalica** [comment]
Where is define line 51 in original src/define.js ?

**Comment by zerkalica** [comment]
In 1.3.11 i add some assertions in development env.
